config/routes.rb
Rails.application.routes.draw do
  root 'root#index'
  get 'root/company', to: 'root#company'
  get 'root/lifesupport', to: 'root#lifesupport'
  get 'root/recovery', to: 'root#recovery'
  get 'root/cleaning', to: 'root#cleaning'
  get 'root/performance', to: 'root#performance'
  get 'root/info', to: 'root#info'
  post 'root/confirm' ,to: 'root#confirm'
  post 'root/thanks',to: 'root#thanks'
  get 'root/plan', to: 'root#plan'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name_full,
    length: { minimum: 1, maximum: 10 };
  validates :name_cana,
    length: { minimum: 1, maximum: 10 };
  validates :phone,
  # phoneは数字のみ許可。ハイフンやカッコは認めない
  numericality: { only_integer: true};
  validates :zip1, presence: true;
  validates :zip2, presence: true;
  validates :address1, presence: true;
  validates :address2, presence: true;
  enum addresses:{
    "---":"",
    北海道:"北海道",青森県:"青森県",岩手県:"岩手県",宮城県:"宮城県",秋田県:"秋田県",山形県:"山形県",福島県:"福島県",
    茨城県:"茨城県",栃木県:"栃木県",群馬県:"群馬県",埼玉県:"埼玉県",千葉県:"千葉県",東京都:"東京都",神奈川県:"神奈川県",
    新潟県:"新潟県",富山県:"富山県",石川県:"石川県",福井県:"福井県",山梨県:"山梨県",長野県:"長野県",
    岐阜県:"岐阜県",静岡県:"静岡県",愛知県:"愛知県",三重県:"三重県",
    滋賀県:"滋賀県",京都府:"京都府",大阪府:"大阪府",兵庫県:"兵庫県",奈良県:"奈良県",和歌山県:"和歌山県",
    鳥取県:"鳥取県",島根県:"島根県",岡山県:"岡山県",広島県:"広島県",山口県:"山口県",
    徳島県:"徳島県",香川県:"香川県",愛媛県:"愛媛県",高知県:"高知県",
    福岡県:"福岡県",佐賀県:"佐賀県",長崎県:"長崎県",熊本県:"熊本県",大分県:"大分県",宮崎県:"宮崎県",鹿児島県:"鹿児島県", 
    沖縄県:"沖縄県"
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
  def company
  end
  def lifesupport
  end
  def recovery
  end
  def cleaning
  end
  def performance
  end
  def info
    @contact = Contact.new
    render  action: "info"
  end

  def confirm
    # 入力値のチェック
    @contact = Contact.new(contact_params)
    if @contact.valid?
      # OK。確認画面を表示
      render action: 'confirm'
    else
      # NG。入力画面を再表示
      render action: 'info'
    end
  end
 
  def thanks
    
    if params[:send]      
      # 送信が押されれば完了画面
      # メール送信
      @contact = Contact.new(contact_params)
      ContactMailer.received_email(@contact).deliver
      
      render action: 'thanks'
    elsif params[:back]
      # 戻る画面が押されれば入力画面
      @contact = Contact.new(contact_params)
      render action: 'info'
    end
  end
  def plan
  end
  private
  def contact_params
    params.require(:contact).permit(:name_full, :name_cana, :phone, :email, :zip1, :zip2, :address1, :address2, :address3, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: '株式会社天授',
      title: '滋賀の遺品整理・生前整理なら『天授』',
      reverse: true,
      charset: 'utf-8',
      description: '住空間の整理サービスなら『天授』にお任せください。遺品整理・生前整理から不用品回収まで幅広いサービスを承っております。ただ物を整理するのが私たちの仕事ではありません。お客様の心を前向きにするお手伝いをさせていただきます。',
      keywords: '遺品整理, 滋賀 遺品整理, 彦根 遺品整理',
      canonical: 'https://tenju.net',
      separator: '|',
      icon: [
        { href: image_url('favicon.ico') },
        { href: image_url('square.png'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/png' },
      ],
      og: {
        site_name: '株式会社天授',
        title: '滋賀の遺品整理・生前整理なら『天授』', 
        description: '住空間の整理サービスなら『天授』にお任せください。遺品整理・生前整理から不用品回収まで幅広いサービスを承っております。ただ物を整理するのが私たちの仕事ではありません。お客様の心を前向きにするお手伝いをさせていただきます。',
        type: 'website',
        url: 'https://tenju.net',
        image: image_url('square.png'),
        locale: 'ja_JP',
      }
    }
  end
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    = analytics_init if Rails.env.production?
    = display_meta_tags(default_meta_tags)
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    %script{ charset: 'UTF-8', src: 'https://ajaxzip3.github.io/ajaxzip3.js'}
    %link(rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:400,700|Noto+Sans+JP:400,700")/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'share/header'
    = yield
    = render 'share/main-footer'
    = render 'share/footer'

app/views/root/_error-messages.html.haml
.error
  - if contact.errors.any?
    - unless contact.valid?
      - if errors = contact.errors.full_messages_for(column.to_sym)
        %ul
          - errors.each do |error|
            %li=error 

app/views/root/cleaning.html.haml
- set_meta_tags title: '滋賀の生前整理なら『天授』', description: "生前整理サービスなら『天授』にお任せください。お客様のご予算に合わせ、最適なプランをご提案をさせていただくことが可能です。また、当社では同じ担当スタッフが最初から最後まで丁寧にサポートさせていただきます。ぜひ一度お問い合わせください。", keywords: "生前整理, 滋賀, 彦根"

.service_main
  .service_main__photo
    = image_tag "flower.jpg", alt:"花の写真"
    .service_main__photo__title
      %span 家財整理・生前整理

    - breadcrumb :cleaning
    = render 'share/breadcrumb'

.service_contents
  .service_contents__title
    %span 家財整理について
  .service_contents__container
    .service_contents__container__photo
      =image_tag "carry.jpg", alt:"荷物を運ぶ人"
    .service_contents__container__textbox
      .service_contents__container__textbox__title
        %span 家の中をスッキリさせたい
      .service_contents__container__textbox__description
        %span
          物がどんどん増えて一度家の中を片付けたい。でも時間がない。重たい物が運べない。整理したいがなかなか行動におこせない。
          %br
          家の中の片付けはとにかく大変なものです。少量の片付けから家一軒まるごとまでお任せください。不要な物がなくなると本当にスッキリします。
          %br
          買取できるものは買取し少しでもお客様のご負担を軽減、リュースやリサイクルできる物を経験豊かなスタッフがしっかり仕分けしてまいります。

  .service_contents__title
    %span ご利用料金
  .service_contents__fee
    .plan__contents__body__reference.inner
      %h3 家財整理の参考価格
      = render 'share/fee/household-goods-fee'
  .service_contents__title
    %span お得なパック料金
  .service_contents__fee
    .plan__contents__body__reference.inner
      = render 'share/fee/pack-fee'
  .service_contents__title
    %span 参考事例
= render 'share/case/case-household-goods'

.service_contents
  .service_contents__title
    %span 生前整理について
  .service_contents__container
    .service_contents__container__photo
      =image_tag "before.jpg", alt:"笑顔の家族"
    .service_contents__container__textbox
      .service_contents__container__textbox__title
        %span 大きな家財も片付けます
      .service_contents__container__textbox__description
        %span
          元気なうちに身のまわりの整理をしておきたい。施設入所することになったので片付け荷作りなど手伝ってほしい。子ども達や親族、ご近所さんには迷惑をかけないようにしたい。
          %br
          そう思うのは親心であり、大切な人たちにできるだけ負担をかけたくないという想いは誰しもが少なからずもっていることでしょう。
          %br
          私達は、そのお気持ちに寄り添いご依頼者様のご納得のいくお手伝いをさせていただきます。

  .service_contents__title
    %span ご利用料金
  .service_contents__fee
    .plan__contents__body__reference.inner
      %h3 生前整理の参考価格(整理作業費・処理費・簡易清掃費含む)
      = render 'share/fee/before-birth-fee'
  .service_contents__title
    %span お得なパック料金
  .service_contents__fee
    .plan__contents__body__reference.inner
      = render 'share/fee/pack-fee'
  .service_contents__title
    %span 参考事例
= render 'share/case/case-before-birth'

app/views/root/done.html.haml
.done
  %div
    %h2 メッセージ送信完了
    %p
      メッセージをいただきありがとうございました。

app/views/root/index.html.haml
.index
  .index__container
    .index__container__image
      = image_tag 'top_image.jpg', alt: 'PCを持った女性'
      .index__container__image__text-zone
        .index__container__image__text-zone__catch
      .index__container__image__info-box
        .index__container__image__info-box__title
          %span 新着のお知らせ
        .index__container__image__info-box__content
          %span.title
            大切なお客様へ、新型コロナウィルスへの対応につきまして
          %span.title
            ・代行サービス
          %span.discription
            　極力外出を控えたいというお客様のために、買い物代行サービス等の生活支援サービスを実施しております。ご要望の方はフリーダイヤルまたは、お問い合わせフォームにてご連絡いただきますようよろしくお願い申し上げます。
          %span.title
            ・消臭・除菌サービス
          %span.discription
            　弊社では現在、除菌・消毒作業依頼を承っております。企業・福祉施設・飲食店などの経営者様からのご依頼が増えています。ドアノブやエレベータのボタンなどたくさんの人が触れる箇所を自社で除菌・消毒をしているが、定期的にプロの技術で徹底的に消毒して欲しい等、ご要望がございましたらぜひ一度ご相談ください。

    .index__container__pick-up
      .index__container__pick-up__content
        = image_tag 'disinfection.jpg', alt: '消毒'
        .index__container__pick-up__content__right
          .index__container__pick-up__content__right__box
            %p.title
              消臭消毒サービス実施中！
            = link_to root_info_path do
              %span
                お問い合わせはこちら
                = fa_icon 'angle-double-right'

    .index__container__step
      .index__container__step__title
        %span ご利用の流れ
      .index__container__step__content
        .index__container__step__content__up
          .index__container__step__content__up__first
            = image_tag 'call.jpg', alt: '電話をする女性'
            .title-zone
              .title-zone__title-box
                %span.step
                  STEP1-
                %span.title
                  お問い合わせ
              .title-zone__discription-box
                %span
                  = link_to root_info_path do
                    ご相談・お見積り
                %span
                  フォーム、またはフリーコールにてご希望の要件をお伝えください。当社スタッフより原則２営業日以内にご連絡させて頂き、ご要望を承ります。
          .index__container__step__content-responsive
            %span
              = link_to root_info_path do
                ご相談・お見積り
            %span
              フォーム、またはフリーコールにてご希望の要件をお伝えください。当社スタッフより原則２営業日以内にご連絡させて頂き、ご要望を承ります。
          .index__container__step__content__up__second
            = image_tag 'calc.jpg', alt: '計算をする女性'
            .title-zone
              .title-zone__title-box
                %span.step STEP2-
                %span.title お見積り
              .title-zone__discription-box
                %span
                  当社スタッフが現地へお伺いさせていただきます。現場確認後、最終見積もりをご提示させて頂き、ご承諾いただければそのまま打ち合わせに移ります。
          .index__container__step__content-responsive
            %span
              当社スタッフが現地へお伺いさせていただきます。現場確認後、最終見積もりをご提示させて頂き、ご承諾いただければそのまま打ち合わせに移ります。
        .index__container__step__content__down
          .index__container__step__content__down__third
            = image_tag 'meeting.jpg', alt: '会話をする女性' 
            .title-zone
              .title-zone__title-box
                %span.step STEP3-
                %span.title お打ち合わせ
              .title-zone__discription-box
                %span
                  お客様の心に寄り添うため、事前のお打ち合わせにて詳細なご要望のヒアリングをさせて頂きます。大切な時間ですので、ご協力よろしくお願い申し上げます。
          .index__container__step__content-responsive
            %span
              お客様の心に寄り添うため、事前のお打ち合わせにて詳細なご要望のヒアリングをさせて頂きます。大切な時間ですので、ご協力よろしくお願い申し上げます。
          .index__container__step__content__down__fourth
            = image_tag 'clean.jpg', alt: '計算をする女性'
            .title-zone
              .title-zone__title-box
                %span.step STEP4-
                %span.title 作業着手
              .title-zone__discription-box
                %span
                  事前打ち合わせの内容をもとに、実際に作業を開始させていただきます。最後まで丁寧な作業を心がけておりますのでご安心ください。
          .index__container__step__content-responsive
            %span
              事前打ち合わせの内容をもとに、実際に作業を開始させていただきます。最後まで丁寧な作業を心がけておりますのでご安心ください。

    .index__container__solve            
      .index__container__solve__title
        %span
          当社の１０
        %span
          = image_tag 'ten.jpg', alt: 'ten', height: '25px', width: '45px'
        %span 
          の強み
      .index__container__solve__content
        .index__container__solve__content__list
          .index__container__solve__content__list__inner
            = fa_icon 'check'
            %span
              優良事業所として認定・有資格者が在籍
          .index__container__solve__content__list__inner
            = fa_icon 'check'
            %span
              一般廃棄物・産業廃棄物・古物商の許認可をもち法令遵守
          .index__container__solve__content__list__inner
            = fa_icon 'check'
            %span
              小さい会社ならではの融通の良さ
          .index__container__solve__content__list__inner
            = fa_icon 'check'
            %span
              ご予算に合わせ、無駄を省き低料金になるようアドバイス
          .index__container__solve__content__list__inner
            = fa_icon 'check'
            %span
              忙しくお時間のないご依頼者さまの負担を軽減
          .index__container__solve__content__list__inner
            = fa_icon 'check'
            %span
              遠く離れたご家族の状況が知れる安心
          .index__container__solve__content__list__inner
            = fa_icon 'check'
            %span
              女性スタッフの在籍・女性ならではの細やかな気配り
          .index__container__solve__content__list__inner
            = fa_icon 'check'
            %span
              ご遺品の模索・整理は誠意をもって丁寧に
          .index__container__solve__content__list__inner
            = fa_icon 'check'
            %span
              ご依頼者さまの心に寄り添う、きめ細やかさ
          .index__container__solve__content__list__inner
            = fa_icon 'check'
            %span
              経験豊富なスタッフが在籍
          
    .index__container__service
      .index__container__service__title
        %span サービスのご案内
      .index__container__service__content
        .index__container__service__content__menu
          .index__container__service__content__menu__recovery
            = image_tag 'family.jpg', alt: '語らう三世代家族'
            = link_to root_recovery_path do
              %p.title
                = fa_icon 'check-circle'
                遺品整理
            %span.discription
              遺品はただの物ではありません。わたしたちは、お客様のニーズに合わせた親切・丁寧な対応を心がけています。
          .index__container__service__content__menu__cleaning
            = image_tag 'baggage.png', alt: '荷物を積んだ軽トラ'
            = link_to root_cleaning_path do
              %p.title
                = fa_icon 'check-circle'
                家財整理
            %span.discription
              生前整理、不用品整理など、身の回りのものを整理することで心も前向きになれるお手伝いを致します。
          .index__container__service__content__menu__lifesupport
            = image_tag 'support.jpg', alt: '家事をする女性'
            = link_to root_lifesupport_path do
              %p.title
                = fa_icon 'check-circle'
                生活サポート
            %span.discription
              お買い物の代行からお墓のお掃除代行まで、お客様のご要望にとことんお応えします。

    .index__container__worries
      .index__container__worries__title
        %span こんなお困りごとはありませんか？
      .index__container__worries__content
        .index__container__worries__content__inner
          .index__container__worries__content__inner__left
            %ul.index__container__worries__content__inner__left__list
              %li 予算内だけで依頼したいので相談に乗って欲しい
              %li 遺品や不用品が多すぎて自分達だけでは整理できない
              %li 子どもに迷惑を掛けたくないので今の内に整理したい
              %li 重いものが運べないのでそれだけでも手伝って欲しい
              %li 遠方に住んでいて何度も実家に通い整理できない
              %li 大切な人との別れが辛く整理する気分になれない
              %li 家屋の解体や売却前に不用品と必要品の整理をしたい
              %li 賃貸で家賃がかかるので一日でも早く片付けたい
              %li とにかく何から手をつけていいのか分からない
              %li なるべく男性より女性スタッフに対応して欲しい
          .index__container__worries__content__inner__right
            .index__container__worries__content__inner__right__image
              = image_tag 'advice.jpg', alt: 'カウンセリングする女性'
        .index__container__worries__content__inner-responsive
          .index__container__worries__content__inner-responsive__image
            = image_tag 'advice.jpg', alt: 'カウンセリングする女性'
          %ul.index__container__worries__content__inner-responsive__list
            %li 予算内だけで依頼したいので相談に乗って欲しい
            %li 遺品や不用品が多すぎて自分達だけでは整理できない
            %li 子どもに迷惑を掛けたくないので今の内に整理したい
            %li 重いものが運べないのでそれだけでも手伝って欲しい
            %li 遠方に住んでいて何度も実家に通い整理できない
            %li 大切な人との別れが辛く整理する気分になれない
            %li 家屋の解体や売却前に不用品と必要品の整理をしたい
            %li 賃貸で家賃がかかるので一日でも早く片付けたい
            %li とにかく何から手をつけていいのか分からない
            %li なるべく男性より女性スタッフに対応して欲しい

app/views/root/info.html.haml
:javascript
  addToNewUrl();

- set_meta_tags title: 'お問い合わせフォーム', noindex: true

.service_main
  .service_main__photo
    = image_tag "info_image.jpg", alt:"花の写真"
    .service_main__photo__title
      %span ご相談・お見積り
    - breadcrumb :info
    = render 'share/breadcrumb'

.service_contents
  .service_contents__title
    %span 無料相談・お見積り
  .info-discription
    %span お問い合わせいただいてから、原則２営業日内に当社スタッフよりお返事させていただきます。
  .info-error
    = render partial: 'error-messages', locals: {contact: @contact, column: "name_full"}
    = render partial: 'error-messages', locals: {contact: @contact, column: "name_cana"}
    = render partial: 'error-messages', locals: {contact: @contact, column: "email"}
    = render partial: 'error-messages', locals: {contact: @contact, column: "phone"}
    = render partial: 'error-messages', locals: {contact: @contact, column: "zip1"}
    = render partial: 'error-messages', locals: {contact: @contact, column: "zip2"}
    = render partial: 'error-messages', locals: {contact: @contact, column: "address1"}
    = render partial: 'error-messages', locals: {contact: @contact, column: "address2"}
    = render partial: 'error-messages', locals: {contact: @contact, column: "content"}
  %form.info
  = form_with model: @contact, url: root_confirm_path,local: true do |f|
    .info__title
      %span お客さま情報
    .info__form
      .info__form__name
        .info__form__name__title
          %span お名前
          %span.must 必須
        .info__form__name__content
          = f.text_field :name_full, class: "form-box", placeholder: "例)小嶋 祥介",id: "name_full"
      .info__form__name
        .info__form__name__title
          %span フリガナ
          %span.must 必須
        .info__form__name__content
          = f.text_field :name_cana ,class: "form-box", placeholder: "例)コジマ ヨシユキ",id:"name_cana"
      .info__form__number
        .info__form__number__title
          %span お電話番号
          %span.must 必須
        .info__form__number__content
          = f.telephone_field :phone, class: "form-box", placeholder: "例)090-1234-5678"
      .info__form__mail
        .info__form__mail__title
          %span メールアドレス
          %span.self 任意
        .info__form__mail__content
          = f.email_field :email, class: "form-box", placeholder: "例)tenju.eco@gmail.com"
      .info__form__address
        .info__form__address__title
          %span 現地ご住所
          %span.must 必須
        .info__form__address__content
          .info__form__address__content__post
            %span 〒
            = f.text_field :zip1, class: "form-box postcode-box"
            %span ー
            = f.text_field :zip2, onKeyUp: "AjaxZip3.zip2addr('contact[zip1]', 'contact[zip2]', 'contact[address1]', 'contact[address2]');", class: "form-box postcode-box"
          .select-box
            = f.select :address1, options_for_select(Contact.addresses), {},{class: "form-box prefecture-box"}
          = f.text_field :address2, placeholder: "市区町村", class: "form-box city-box"
          = f.text_field :address3, placeholder: "番地・建物名", class: "form-box address-box"
      .info__form__detail
        .info__form__detail__title
          %span お問い合わせ内容
          %span.self 任意
        .info__form__detail__content
          = f.text_area :content,cols: "60", rows: "10", placeholder: "例)生前整理をして頂きたいのですが、平日の午前中に見積もりに来ていただくことは出来ますか？今月中に作業をすませて欲しいので、そちらも可能かどうかお返事いただきたいです。", class: "form-box"
    .info__submit
      .info__submit__attention
        .info__submit__attention__text
          %span.title
            プライバシーポリシー
          %span.discription
            株式会社天授(以下『当社』という)は、個人情報に関する法令の遵守、個人情報の適切な取り扱い及び管理を徹底し、大切な個人情報の保護につとめてまいります。
          %span.sub-title
            個人情報の収集および利用
          %span.discription
            個人情報を収集する際には利用目的をお知らせします。
            %br
            個人情報は、その利用目的をお知らせしてご本人の同意が得られた上でご提供いただきます。ご提供いただいた個人情報は、お知らせした利用目的の範囲を超えて利用しません。
          %span.discription
            利用目的の範囲について
            %br
            ・業務上のご連絡をする場合
            %br
            ・当社が取り扱う商品及びサービスに関するご案内をする場合
            %br
            ・お客様からのお問い合わせまたはご依頼等への対応をさせていただく場合
            %br
            ・その他、お客様に事前にお知らせし、ご同意をいただいた目的の場合
          %span.sub-title
            個人情報の第三者への提供・開示・訂正・消去
          %span.discription
            当社は、お客様の同意なしに第三者へお客様の個人情報の提供は行いません。
            %br
            但し個人情報に適用される法律、その他の規範により、当社が従うべき法令上の義務等の特別な事情がある場合は、この限りではありません。
            %br
            個人情報の開示・訂正・提供範囲の変更や削除を本人から依頼された場合には、合理的な範囲ですみやかに対応します。
          %span.sub-title
            個人情報の安全管理措置
          %span.discription
            徹底した管理によって個人情報の正確性及び安全性を確保します。
            %br
            また、ご提供いただいた個人情報の紛失、破壊、改ざん及び漏洩等の防止に努めます。
            %br
            回収致しました物品に関しても、分別・適切な処理を行い、お客様の個人を特定する情報が残ることはございません。
            %br
            個人情報を扱う業務を他の会社に委託する場合、個人情報を収集するときの承諾に基づく利用、提供、安全管理を守るように、委託先に対する適切な契約や指導・管理をします。
          %span.sub-title
            継続的な改善について
          %span.discription
            当社が保有する個人情報に関して適用される法令、規則を遵守するとともに、適切な運用が実施されるよう管理と必要な是正を行い、個人情報保護の取り組みを継続的に見直し改善実施いたします。

      .info__submit__check
        %label{for: "agree"}
          上記規約内容に同意する
        %input{type: "checkbox", class: "agree"}
      .info__submit__button
        = f.submit "入力内容の確認", class: "submit-btn"

app/views/share/_breadcrumb.html.haml
%nav
  = breadcrumbs pretext: "", separator: " &rsaquo; ", class: "breadcrumb"

app/views/share/_footer.html.haml
.footer
  .footer__btn
  = link_to "tel:0120920678" , class: "footer__contents" do
    %p.footer__contents__title お電話でのお問い合わせはこちら
    .footer__contents__info
      %p.footer__contents__info__tel 0120-920-678
      %p.footer__contents__info__time 【受付時間】8:00~20:00
  = link_to root_info_path , class: "footer__mail" do
    ご相談
    %br.hidden-res
    お見積り

app/views/share/_header.html.haml
.header
  .header__left
    = link_to root_path, class: 'header__left__logo' do
      = image_tag 'logo.png', alt: 'ロゴ', size: '55x55', class: 'logo'
      = image_tag 'logo_text.png', alt: 'ロゴ', size: '100x60', class: 'logo_text'
  .header__right
    .header__right__call
      = image_tag 'freecall.png', alt: 'フリーコール'
      %p 0120-920-678
      %span 【受付時間】8:00~20:00
    %ul.header__right__list
      %li
        = link_to root_recovery_path do
          遺品整理
      %li
        = link_to root_cleaning_path do
          家財整理
      %li
        = link_to root_lifesupport_path do
          生活サポート
      %li
        = link_to root_plan_path do
          料金一覧
      %li
        = link_to root_performance_path do
          作業事例
      %li
        = link_to root_company_path do
          会社概要
      = link_to "ご相談・お見積り", root_info_path, class: "info-button"

.navi
  %ul
    %li
      = link_to "" do
        トップページ
    %li
      = link_to root_path do
        トップページ
    %li
      = link_to root_recovery_path do
        遺品整理
    %li
      = link_to root_cleaning_path do
        家財整理
    %li
      = link_to root_lifesupport_path do
        生活サポート
    %li
      = link_to root_plan_path do
        料金一覧
    %li
      = link_to root_performance_path do
        作業事例
    %li
      = link_to root_company_path do
        会社概要
    %li
      = link_to root_info_path do
        ご相談・お見積り
.header-responsive
  .header-responsive__left
    = link_to root_path do
      .logo
        = image_tag 'logo.png', alt: 'ロゴ', height: '30', width: '30', class: "mark"
        = image_tag 'logo_text.png', alt: 'ロゴ', height: '38', width: '72', class: "text"

  .header-responsive__right
    .toggle
      %span
      %span
      %span

app/views/share/_main-footer.html.haml
.main-footer
  .main-footer__top-btn
    = link_to "▲" , "#wrap" , id: "return-top" , class: "return-top"
  .main-footer__contents.inner
    .main-footer__contents__logo-box
      .main-footer__contents__logo-box__proof
        = image_tag "is1.jpg" , class: 'proof'
        = image_tag "is2.jpg" , class: 'proof'
      
    %nav.main-footer__contents__nav
      %ul.main-footer__contents__nav__list
        %li.main-footer__contents__nav__list__item
          = link_to "トップページ" , root_path
        %li.main-footer__contents__nav__list__item
          = link_to "遺品整理" , root_recovery_path
        %li.main-footer__contents__nav__list__item
          = link_to "家財整理" , root_cleaning_path
        %li.main-footer__contents__nav__list__item
          = link_to "生活支援" , root_lifesupport_path
      %ul.main-footer__contents__nav__list.ul-last
        %li.main-footer__contents__nav__list__item
          = link_to "料金一覧" , root_plan_path
        %li.main-footer__contents__nav__list__item
          = link_to "実績紹介" , root_performance_path
        %li.main-footer__contents__nav__list__item
          = link_to "会社概要" , root_company_path
        %li.main-footer__contents__nav__list__item
          = link_to "ご相談・お見積り" , root_info_path
  %p.main-footer__copyright
    %small Copyright© tenju,Inc All rights reseaved.